### ISSUE TITLE
Add read support

### ISSUE THREAD

**Issue by dancollins** [hannobraun/3mf-rs#19]
I'm looking at building a slicer, mostly as an excuse to try a new pipelined architecture for slicing and to learn some Rust. You library looks like a defacto-standard for 3MF - which is great! - but it's lacking file read support (which will be my primary use-case). I figure we load from the file into the mesh structure you already have, and the user can handle translation into their own structs as needed.

Main question, looking at an STL library, is around the lack or normal vectors. Is this something that's needed? I was under the impression each triangle had a normal face and either that's unique to STLs (3MF triangles are double-sided?) or just currently missing.

I'm very new to Rust and to 3D, but I've got a lofty goal and 3MF is my preferred format over STL. I'd like to expand to include the meta-data (where I can store slicer settings, colours, etc) and this library is a great starting point. Scope of this issue in particular would be feature parity with existing write support, however.

Thoughts?

**Comment by hannobraun** [comment]
Thank you for your interest, @dancollins!

Any contributions that add read support and other 3MF features are very welcome, and everything you describe sounds reasonable.


> Main question, looking at an STL library, is around the lack or normal vectors. Is this something that's needed? I was under the impression each triangle had a normal face and either that's unique to STLs (3MF triangles are double-sided?) or just currently missing.

As far as I remember, triangle orientation is defined by the order of vertices. I believe, the side of the triangle from which the vertices appear counter-clockwise is the outside (i.e. normal is pointing at the observer in that case). A quick search for "normal" in [the specification](https://github.com/3MFConsortium/spec_core/blob/master/3MF%20Core%20Specification.md) seems to support that view.


> I'm very new to Rust and to 3D, but I've got a lofty goal and 3MF is my preferred format over STL. I'd like to expand to include the meta-data (where I can store slicer settings, colours, etc) and this library is a great starting point. Scope of this issue in particular would be feature parity with existing write support, however.

I agree that feature parity with write support would be a good starting point. And as I said, anything going beyond that (like metadata, as you mention) would be very welcome. Just note that I don't currently have a use case for that, nor much extra time to dive into it. So the design and testing for such an effort would have been driven by you.

I'm happy to provide feedback where I can, and through Fornjot's test suite, I can at least make sure that whatever you do doesn't break the current "write without metadata" use case.

---

By the way, adding slicer features to Fornjot is something that I'm interested in, in principle. It's out of scope for now though. Much too early, as things are still in flux, and there's a huge amount of work to do on the CAD side.

**Comment by dancollins** [comment]
Probably worth adding tests to make sure I don't break anything! I have no idea how to do that in Rust - but if it's like all the other stuff I've done it will be easy to pick up :) That will obviously help as long as you and I can craft tests for our use cases.

Integrating slicing into CAD would be cool. My project is AGPL so as long as that license works for you you're welcome to derive/integrate it. Not commiting to finishing it - but it will be a fun project either way!

**Comment by hannobraun** [comment]
> Probably worth adding tests to make sure I don't break anything! I have no idea how to do that in Rust - but if it's like all the other stuff I've done it will be easy to pick up :) That will obviously help as long as you and I can craft tests for our use cases.

Definitely makes sense! So far, the need didn't come up, thanks to the Fornjot test suite.


> Integrating slicing into CAD would be cool. My project is AGPL so as long as that license works for you you're welcome to derive/integrate it. Not commiting to finishing it - but it will be a fun project either way!

That license could work for an optional component, but AGPL code will definitely never make its way into the core project.

**Comment by hannobraun** [comment]
In #22, @Mik-pe switched 3MF writing code to use [Serde](https://crates.io/crates/serde). This brings us closer to read support, as it's possible to re-use the same structs used for writing.

@Mik-pe also created [a branch for read support](https://github.com/Mik-pe/3mf-rs/tree/serde-read), but didn't have time to finish it. Any help here is appreciated!
